name: Upload PDF to Mega Cloud

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the main branch
  workflow_dispatch:  # Allow the workflow to be triggered manually

jobs:
  download-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get install -y poppler-utils
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download files from Mega
        env:
          M_TOKEN: ${{ secrets.M_TOKEN }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
        run: |
          python download_files.py

     

      # Optional: Set up Python 3.12, if needed for another part of the process
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies (Python 3.12)
        run: |
          sudo apt-get install -y poppler-utils
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Process and upload files
        env:
          M_TOKEN: ${{ secrets.M_TOKEN }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
        run: |
          python process_and_upload.py
