name: Upload PDF to Mega Cloud

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the main branch
  workflow_dispatch:  # Allow the workflow to be triggered manually

jobs:
  upload-to-mega:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.6'  # Use Python 3.10 for compatibility
      
      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get install -y poppler-utils

          python -m pip install --upgrade pip
          pip install -r requirements.txt



      
      # Step 6: Run the Python script
      - name: Run upload script
        env:
          M_TOKEN: ${{ secrets.M_TOKEN }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
        run: |
          python water_mark_video.py
